remote_theme: pages-themes/hacker

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  '@typed/fp on GitHub':
    - 'https://github.com/TylorS/typed-fp#readme'
theme: jekyll-theme-hacker